<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-04-18T13:03:39Z" name="Default suite" finished-at="2019-04-18T13:04:34Z" duration-ms="55097">
    <groups>
    </groups>
    <test started-at="2019-04-18T13:03:39Z" name="Default test" finished-at="2019-04-18T13:04:34Z" duration-ms="55097">
      <class name="ngpack.NewTest">
        <test-method signature="passParameters()[pri:0, instance:ngpack.NewTest@123f1134]" started-at="2019-04-18T13:03:39Z" name="passParameters" finished-at="2019-04-18T13:04:14Z" duration-ms="34726" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passParameters -->
        <test-method signature="openURLNew()[pri:0, instance:ngpack.NewTest@123f1134]" started-at="2019-04-18T13:04:14Z" name="openURLNew" finished-at="2019-04-18T13:04:34Z" depends-on-methods="ngpack.NewTest.passParameters" duration-ms="20324" status="FAIL">
          <exception class="java.lang.ExceptionInInitializerError">
            <full-stacktrace>
              <![CDATA[java.lang.ExceptionInInitializerError
at org.sikuli.script.Region.<init>(Region.java:60)
at org.sikuli.script.Screen.<init>(Screen.java:132)
at allclasses.commonParaFun.createNew(commonParaFun.java:76)
at ngpack.NewTest.openURLNew(NewTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 2, end 3, length 2
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3410)
at java.base/java.lang.String.substring(String.java:1883)
at org.sikuli.basics.Settings.<clinit>(Settings.java:115)
... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ExceptionInInitializerError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openURLNew -->
      </class> <!-- ngpack.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
